# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrs_1.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_myip_0_0/design_1_myip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_myip_0_0 || ORIG_REF_NAME==design_1_myip_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UIF_AXI_0_0/design_1_UIF_AXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_UIF_AXI_0_0 || ORIG_REF_NAME==design_1_UIF_AXI_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fifo_generator_0_3/design_1_fifo_generator_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_0_3 || ORIG_REF_NAME==design_1_fifo_generator_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_1_0 || ORIG_REF_NAME==design_1_fifo_generator_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UIF_SerialSlave_0_2/design_1_UIF_SerialSlave_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_UIF_SerialSlave_0_2 || ORIG_REF_NAME==design_1_UIF_SerialSlave_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UIF_SerialMasterCont_0_0/design_1_UIF_SerialMasterCont_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_UIF_SerialMasterCont_0_0 || ORIG_REF_NAME==design_1_UIF_SerialMasterCont_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_DSP_registers_0_0/design_1_DSP_registers_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_DSP_registers_0_0 || ORIG_REF_NAME==design_1_DSP_registers_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xfft_0_0/design_1_xfft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xfft_0_0 || ORIG_REF_NAME==design_1_xfft_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FFTInputBitsConverter_0_0/design_1_FFTInputBitsConverter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_FFTInputBitsConverter_0_0 || ORIG_REF_NAME==design_1_FFTInputBitsConverter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FFTOutputBitsConvert_0_0/design_1_FFTOutputBitsConvert_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_FFTOutputBitsConvert_0_0 || ORIG_REF_NAME==design_1_FFTOutputBitsConvert_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0_1/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_2_1/design_1_blk_mem_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_2 || ORIG_REF_NAME==design_1_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0_1/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_3/design_1_axi_bram_ctrl_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_3 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_source_0/design_1_axi_bram_ctrl_source_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_source_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_source_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_prescaler_0_0/design_1_prescaler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_prescaler_0_0 || ORIG_REF_NAME==design_1_prescaler_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_1_1/design_1_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_1 || ORIG_REF_NAME==design_1_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UIF_AXI_0_1/design_1_UIF_AXI_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_UIF_AXI_0_1 || ORIG_REF_NAME==design_1_UIF_AXI_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UIF_SerialSlave_1_0/design_1_UIF_SerialSlave_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_UIF_SerialSlave_1_0 || ORIG_REF_NAME==design_1_UIF_SerialSlave_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UIF_SerialMasterCont_0_1/design_1_UIF_SerialMasterCont_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_UIF_SerialMasterCont_0_1 || ORIG_REF_NAME==design_1_UIF_SerialMasterCont_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fifo_generator_2_0/design_1_fifo_generator_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_2_0 || ORIG_REF_NAME==design_1_fifo_generator_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fifo_generator_3_0/design_1_fifo_generator_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_3_0 || ORIG_REF_NAME==design_1_fifo_generator_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UIF_AXI_0_2/design_1_UIF_AXI_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_UIF_AXI_0_2 || ORIG_REF_NAME==design_1_UIF_AXI_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UIF_SerialSlave_1_1/design_1_UIF_SerialSlave_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_UIF_SerialSlave_1_1 || ORIG_REF_NAME==design_1_UIF_SerialSlave_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UIF_SerialMasterCont_0_2/design_1_UIF_SerialMasterCont_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_UIF_SerialMasterCont_0_2 || ORIG_REF_NAME==design_1_UIF_SerialMasterCont_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fifo_generator_2_1/design_1_fifo_generator_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_2_1 || ORIG_REF_NAME==design_1_fifo_generator_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fifo_generator_3_1/design_1_fifo_generator_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_3_1 || ORIG_REF_NAME==design_1_fifo_generator_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_5/design_1_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_5 || ORIG_REF_NAME==design_1_auto_pc_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2_1/design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_3 || ORIG_REF_NAME==design_1_auto_pc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_4_1/design_1_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_4 || ORIG_REF_NAME==design_1_auto_pc_4} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
